# Generated by Django 3.1.7 on 2021-03-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.IntegerField(unique=True)),
                ('fechanacimiento', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tipodocumento')),
                ('lugarresidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.ciudad')),
            ],
        ),
    ]
